function FlightData = importFlightData(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  FLIGHTDATA = IMPORTFILE2(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the data as
%  a table.
%
%  FLIGHTDATA = IMPORTFILE2(FILE, SHEET) reads from the specified
%  worksheet.
%
%  FLIGHTDATA = IMPORTFILE2(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  FlightData = importfile2("C:\Users\Ing-Aplicaciones\Desktop\Drive James Quiroz\James Quiroz\Presentations\PPT\DataAnalysis\Low code\Code\FlightData.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jul-2023 11:30:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["Time", "FuelQuantity", "OilPressure", "OilTemperature", "LatitudePosition", "LongitudePosition", "Altitude", "ExhaustTemperature", "FuelFlow", "FanSpeed", "TrueAirSpeed", "WindDirection", "WindSpeed", "WeightOnWheels"];
opts.VariableTypes = ["datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
FlightData = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    FlightData = [FlightData; tb]; %#ok<AGROW>
end

end